name: muzik_player
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  go_router: ^12.1.1
  hugeicons: ^0.0.10
  marquee: ^2.3.0
  on_audio_query: ^2.9.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf

